typography_spectrum: 0.9954852680675685
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8402702875901014
  lightness: 0.08481607353314757
  saturation: 0.32571507850661874
  rhythmicContrast: 0.6487665707245469
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9981136748101562
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: IT Design
  email: biuro@itdesign.com.pl
  url: www.itdesign.com.pl
name: fibaro
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: IT Design
    url: 'http://www.itdesign.com.pl'
    type: external
favicon: null
title: IT Design
purpose: []
